pipeline:
  build:
    image: python:${TAG}-alpine
    commands:
      # Install build dependencies
      - apk add --no-cache gcc musl-dev

      # Install dependencies
      - pip install -r requirements.txt
      - pip install .

      # Run tests
      - pytest

    when:
      event: push

matrix:
  TAG:
    - 3.8   # EOL/SS 2024-10-14
    - 3.9   # EOL/SS 2025-10-05
    - 3.10  # EOL/SS 2026-10-04
    - 3.11  # EOL/SS 2027-10-24
